### ISSUE TITLE
Add panel for current active invocations

### ISSUE THREAD

**Issue by wagnerjt** [LlemonDuck/tombs-of-amascut#21]
Inside the raid it'd be nice to see the list of invocations that were set during the start.

Good examples:
* When the raid ends and someone leaves first, the invocations are set to that person's presets. 
* Stepping away and invocations were changes
* Logging in for WDR

**Comment by LlemonDuck** [comment]
Unfortunately the invocations are only synced to the client when the interface is open, and unless you had the invocation panel open at the time they were changed, the client has no way to know which invocations are enabled. Jagex simply does not transmit this information when the interface is not visible.

For this reason, I think an invocation list on the sidebar (while likely to be correct *most* of the time) would add a lot of confusion when it is incorrect, and enough confusion that it would not be worth adding. If it otherwise becomes possible to track invocations without the panel, I am willing to revisit this.

**Comment by wagnerjt** [comment]
I only briefly looked into the varbits that were exposed and wasn't quite sure. 

I guess the only guarantee is if you are the party leader and have opened the invo board before going in. Better to avoid it all together
