### ISSUE TITLE
"efficient" kephri puzzle

### ISSUE THREAD

**Issue by Reeenatu** [LlemonDuck/tombs-of-amascut#30]
![image](https://user-images.githubusercontent.com/16688838/194674951-2a159e7b-ff17-41f0-821d-40f4fcb8bb61.png)
It would be nice to add a config to choose these tiles instead of the current ones.

**Comment by blismatic** [comment]
Bump to this. Would be a really good QoL feature, and could even label the "yellow" tiles with numbers (e.g 1, 2, 3, 4) to make it even more clear the order to click.

![There is also this image for efficient/easy tiles](https://user-images.githubusercontent.com/14958849/210639880-13087696-c2d3-4ce4-bc52-73eb2d0d7671.png) but it assumes that you start next to the tablet, instead of 1 tile south of it.

**Comment by LlemonDuck** [comment]
Partially solved by #46, but does not show you which tiles to click, nor order. Willing to merge this in if someone creates a PR, but probably won't get to it myself any time soon.

**Comment by LlemonDuck** [comment]
added the above in daadc1d1b1c2d7f7a0ac932c89e183b4af2ef681
