### ISSUE TITLE
ToA Points lost on death

### ISSUE THREAD

**Issue by purush97** [LlemonDuck/tombs-of-amascut#77]
The dev blog post talking about toa drop mechanics says you lose 20% of your points on death, but having watched recent ToA deaths of mine, the points overlay is taking away fewer points than that. I can provide videos of a handful of ToA deaths from the past week but the overlay seems to deduct closer to 15% of your current points on a death.

Unsure if there was further information from Jmods that I missed for this to be the case, or the plugin is miscalculating or something

**Comment by LlemonDuck** [comment]
The plugin displays "total" points with a bit of hidden magic going on behind the scenes that would muddy this and appear to be doing the math "wrong":
* You actually start the raid with 5k points to make early deaths not meaningless, but the plugin hides this since it's subtracted at the end before loot is rolled.
* Your current room points and your previous room points are shown together, but computed separately.
* MVPs and some other things that can't be attributed to any single player are not included in death subtractions, since I can't reliably determine whose death they should apply to.

That said, I did actually get some more info from jmods just this past week which illuminated a couple areas in which the plugin is wrong, but not by much. I'll be fixing them shortly.
