### ISSUE TITLE
Custom purple sound when entering treasure room

### ISSUE THREAD

**Issue by Chris-Watters95** [LlemonDuck/tombs-of-amascut#87]
Would be nice to be able to set a custom sound when entering the sarcophagus room if a purple dropped rather than when the chest is opened, similar to the odablock plugin.

**Comment by DapperMickie** [comment]
Not 100% related to your question, but since you mentioned the odablock plugin I'll respond.
If you have the odablock plugin installed, you can customize the sound by going to the folder where I store the sounds (should be something like %USERPROFILE%/.runelite/odablock-sounds and locate the folder for the sound you want to replace (in this case "gettingpurple") then go in the "custom" folder and add your sound file there (must be .wav format). This changes the sound for cox/tob too btw.

**Comment by LlemonDuck** [comment]
Assuming that works ^ I'd rather not duplicate that plugin's functionality.
